### PR TITLE
Cut

### PR DESCRIPTION
**Pull request by Misty418**
For now we can cut one sample at a time.

For multiple selection, we could use it like this :
we select samples (for example five)
we apply the cut tool on one of them ( for example a sample with 7 of duration)
Suppose it cuts the sample and shorten it to a duration of 3, the new sample is 4. For the others samples selected, it will shorten all of them to 3s of duration if they are longer than 3s. It will have no effects one samples less than 3s.
is it ok?

### CODE REVIEW

**Comment by Misty418** [comment]
@Mr21 
Is it ok? Can I push on master?

**Comment by Mr21** [comment]
I have tested it, we'll have to add a visual feedback, but I love the way how it's working right now, it's awesome!
All the HTML of the project is inside the new `templates/` folder, we now use Handlebars.

To remove any conflict, can you undo your change on `Sample/moveX.js` and not push the `compressed.js` file.

**Comment by Mr21** [comment]
I've push some coding style details, and undo a miss change of `moveX.js`.

**Comment by Misty418** [comment]
@Mr21 Ok, I merged the last version of master with this branch, and I made the changes.
So now I'll apply all these changes on master but before, what's the problem with gridsound.github.io?

**Comment by Mr21** [comment]
>   what's the problem with gridsound.github.io?

It's okay now, I have made a mistake with some compressed filenames like `"__precompiled"`
https://bugzilla.mozilla.org/show_bug.cgi?id=1278225#c4

**Pull request closed without merging**
